import type { Place } from "../types/place";

const mockPlaces: Place[] = [
  {
    id: 1,
    title: "해송 펫스테이",
    address: "제주 제주시 애월읍 애월해안로 120",
    category: "숙소",
    petPolicy: "OK",
    tags: ["해변", "대형견", "산책로"],
    points: ["올레길 7코스 인접", "반려견 전용 샤워룸"],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: true },
      indoorAllowed: true,
      leashRequired: true,
      carrierRequired: false,
      extraFee: true,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
  {
    id: 2,
    title: "루프탑 펫카페 라일락",
    address: "서울 마포구 와우산로 21길 14",
    category: "카페",
    petPolicy: "OK",
    tags: ["루프탑", "디저트", "야경"],
    points: ["댕댕이 전용 간식 제공", "야경 뷰 포토존"],
    image: "https://images.unsplash.com/photo-1507138451611-3001135909fa?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: true,
      leashRequired: true,
      carrierRequired: false,
      extraFee: false,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
  {
    id: 3,
    title: "도담 반려식당",
    address: "부산 해운대구 마린시티2로 33",
    category: "식당",
    petPolicy: "OK",
    tags: ["브런치", "테라스", "예약"],
    points: ["펫 메뉴 주문 가능", "예약 시 창가 우선"],
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: false,
      extraFee: true,
      maxPets: 1,
      catIndoorOnly: true,
    },
  },
  {
    id: 4,
    title: "솔빛 전망대",
    address: "강원 강릉시 사천면 진리 220",
    category: "관광",
    petPolicy: "OK",
    tags: ["전망", "산책", "노을"],
    points: ["반려견 동반 산책로", "일몰 포인트 안내"],
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: true },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: true,
      extraFee: false,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
  {
    id: 5,
    title: "모래숲 체험장",
    address: "경기 양평군 양서면 양수로 88",
    category: "체험",
    petPolicy: "OK",
    tags: ["자연", "야외", "체험"],
    points: ["안전장비 착용 필수", "펫 대기 공간 별도"],
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: true,
      extraFee: true,
      maxPets: 1,
      catIndoorOnly: true,
    },
  },
  {
    id: 6,
    title: "아늑한 파우더룸",
    address: "대구 수성구 들안로 12길 9",
    category: "숙소",
    petPolicy: "OK",
    tags: ["도심", "조용함", "주차"],
    points: ["소형견 전용 룸 준비중", "공용 구역 동반 제한"],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: true,
      leashRequired: true,
      carrierRequired: true,
      extraFee: true,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
  {
    id: 7,
    title: "은빛 강변 산책로",
    address: "경기 남양주시 다산동 112-4",
    category: "관광",
    petPolicy: "OK",
    tags: ["강변", "산책", "야경"],
    points: ["야간 조명 산책로", "반려견 쉼터 구역 운영"],
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: true },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: true,
      extraFee: false,
      maxPets: 3,
      catIndoorOnly: true,
    },
  },
  {
    id: 8,
    title: "올데이 펫브런치",
    address: "서울 성동구 성수이로 64",
    category: "식당",
    petPolicy: "OK",
    tags: ["브런치", "펫메뉴", "예약"],
    points: ["펫 전용 메뉴 제공", "주말 방문 예약 권장"],
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: false,
      extraFee: true,
      maxPets: 1,
      catIndoorOnly: true,
    },
  },
  {
    id: 9,
    title: "카페 달빛정원",
    address: "전북 전주시 완산구 전주천동로 22",
    category: "카페",
    petPolicy: "OK",
    tags: ["야외", "정원", "디저트"],
    points: ["야외 정원 좌석 운영", "포토존 이벤트 진행"],
    image: "https://images.unsplash.com/photo-1507138451611-3001135909fa?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: true,
      leashRequired: true,
      carrierRequired: true,
      extraFee: false,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
  {
    id: 10,
    title: "솔바람 독채 스테이",
    address: "강원 평창군 봉평면 봉평북로 210",
    category: "숙소",
    petPolicy: "OK",
    tags: ["독채", "바베큐", "대형견"],
    points: ["울타리 있는 마당", "애견 용품 무료 대여"],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: true },
      indoorAllowed: true,
      leashRequired: false,
      carrierRequired: false,
      extraFee: true,
      maxPets: 3,
      catIndoorOnly: true,
    },
  },
  {
    id: 11,
    title: "별빛 목장 체험",
    address: "충남 서산시 대산읍 목장길 15",
    category: "체험",
    petPolicy: "OK",
    tags: ["목장", "체험", "야외"],
    points: ["안전교육 후 입장", "펫 대기 공간 별도"],
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: false,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: false,
      leashRequired: true,
      carrierRequired: true,
      extraFee: false,
      maxPets: 1,
      catIndoorOnly: true,
    },
  },
  {
    id: 12,
    title: "도심 속 펫라운지",
    address: "인천 연수구 센트럴로 12",
    category: "카페",
    petPolicy: "OK",
    tags: ["실내", "라운지", "예약"],
    points: ["예약제 운영", "동반 입장 규정 안내 필수"],
    image: "https://images.unsplash.com/photo-1507138451611-3001135909fa?auto=format&fit=crop&w=900&q=80",
    policy: {
      dogAllowed: true,
      catAllowed: true,
      dogSize: { small: true, medium: true, large: false },
      indoorAllowed: true,
      leashRequired: true,
      carrierRequired: true,
      extraFee: true,
      maxPets: 2,
      catIndoorOnly: true,
    },
  },
];

export const getPlaces = async (): Promise<Place[]> => {
  return mockPlaces;
};

export const getPlaceById = async (id: number): Promise<Place | null> => {
  const places = await getPlaces();
  return places.find((place) => place.id === id) ?? null;
};
